workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
 
variables:
#   DEPLOYMENT_NAME: name   uncomment the line and type the required value
#   KUBE_NAMESPACE: namespace        uncomment the line and type the required value
    
     
deploy:
  stage: deploy
  image: alpine:3.11.5
  script:
    - chmod +x ./worker.sh
    - ./worker.sh