apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: genrptpy-deployment-restart
  namespace: "$KUBE_NAMESPACE"
spec:
  concurrencyPolicy: Forbid
  schedule: '0 1 * * *'        #restart every day at 01:00
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 0
  jobTemplate:
    spec:
      backoffLimit: 2
      activeDeadlineSeconds: 600
      template:
        spec:
          serviceAccountName: deployment-restart
          restartPolicy: Never
          containers:
            - name: kubectl
              image: bitnami/kubectl
              command:
                - 'kubectl'
                - 'rollout'
                - 'restart'
                - 'deployment/DEPLOYMENT_NAME'