apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deployment-restart
  namespace: "$KUBE_NAMESPACE"
rules:
  - apiGroups: ["", "apps", "extensions"]
    resources: ["deployments", "replicasets", "pods"]
    verbs: ["get", "patch", "list", "watch" , "create" , "delete", "update"]